### ISSUE TITLE
supported color list

### ISSUE THREAD

**Issue by sukhitashvili** [aleferna12/colordict#3]
Hi, 

Thanks for the useful package!
Could you tell me where I can find a list of all the supported colors?

Thanks!

**Comment by aleferna12** [comment]
Hey!

This package is not being actively maintained, so I suggest using [colorir](https://colorir.readthedocs.io/) instead, as it has a more complete documentation including a list of palettes available.

However, you can get a list of colors in a colordict by casting it to a list:
```
colors = ColorDict()
list(colors)
```
